# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d76537713cd48b81790e3cc02a35c3befe01dd90b5232fd36197759239ae4519091b4c71f8acfb68369256c06867ae45d52fb53bee19492279ccc39f93a6587

test:
  secret_key_base: 6334cd7692620dc779c731f4e7935cd3d0063cbc46d81735ba4f8426f2eeb974f45de89f4f0ef95160008e0f4cc9b6bb1fe1fb976728436306e8d947c86e3eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
